apiVersion: v1
kind: Namespace
metadata:
  name: test-scale-ns
  labels:
    name: k8-tutorial
---
# This creates a ServiceAccount named test-scale-sa in the test-scale-ns namespace.
# ServiceAccounts are used by pods to interact with the Kubernetes API.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-scale-sa
  namespace: test-scale-ns
  labels:
    name: k8-tutorial
---
# This creates a RoleBinding named test-scale-rb which grants the edit ClusterRole to the test-scale-sa service account.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-scale-rb
  labels:
    name: k8-tutorial
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: test-scale-sa # defined in service-account.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-scale-ns
  labels:
    name: k8-tutorial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: test-scale-sa # secret of this service account will be mounted to the pod
      containers:
        - name: nginxpod
          image: nginx
          ports:
            - containerPort: 80